[build]
  command = "pnpm run build"
  publish = "out/renderer"

[[redirects]]
  from = "/api/ttml/*"
  to = "https://lyrics.qizou.dpdns.org/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://musicapi.qizou.dpdns.org/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
